# Generated by Django 3.2.9 on 2021-12-25 17:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.TextField(max_length=32, verbose_name='Name of genre')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='Number of a hall')),
                ('description', models.TextField(max_length=100, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description of performance')),
                ('author', models.CharField(max_length=64, verbose_name='Author')),
                ('duration', models.DurationField(verbose_name='Duration of performance')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price')),
                ('genre_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100, verbose_name='Description of a rating')),
                ('min_age', models.IntegerField(verbose_name='Minimal age of a visitor')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Level of tier')),
                ('number_of_seats', models.PositiveIntegerField(verbose_name='Number of seats')),
                ('hall_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date of performance')),
                ('hall_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.hall')),
                ('performance_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.performance')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='rating_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.rating'),
        ),
    ]
