# Generated by Django 3.2.9 on 2021-11-24 19:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='description',
            field=models.TextField(default='aa', max_length=100, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='performance',
            name='description',
            field=models.TextField(default='something', verbose_name='Description of performance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.TextField(max_length=32, verbose_name='Name of genre'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='number',
            field=models.CharField(max_length=32, verbose_name='Number of a hall'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='author',
            field=models.CharField(max_length=64, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='duration',
            field=models.DurationField(verbose_name='Duration of performance'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='date',
            field=models.DateTimeField(verbose_name='Date of performance'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='hall_id',
            field=models.ForeignKey(default='aa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.hall'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.TextField(verbose_name='Description of a rating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='min_age',
            field=models.IntegerField(verbose_name='Minimal age of a visitor'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='level',
            field=models.IntegerField(verbose_name='Level of tier'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='number_of_seats',
            field=models.PositiveIntegerField(verbose_name='Number of seats'),
        ),
    ]
