# Generated by Django 3.2.9 on 2021-11-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_auto_20211124_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='hall_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.hall'),
        ),
    ]
