# Generated by Django 3.2.9 on 2021-12-27 01:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('performance', '__first__'),
    ]
    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('phone', phone_field.models.PhoneField(max_length=31, verbose_name='Phone')),
                ('mail', models.CharField(max_length=64, verbose_name='Mail')),
                ('tickets', models.CharField(max_length=64, verbose_name='Tickets')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Ticket price')),
                ('place', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('availability', models.BooleanField(verbose_name='Availability')),
                ('poster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.poster')),
                ('tier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.tier')),
            ],
        ),
    ]
