# Generated by Django 3.2.9 on 2021-12-29 23:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '__first__'),
        ('ticketStore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tickets',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default='31/12/2021', verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='poster_id',
            field=models.IntegerField(default=1, verbose_name='Poster_id'),
        ),
        migrations.AddField(
            model_name='order',
            name='ticket',
            field=models.IntegerField(default=1, verbose_name='Ticket'),
        ),
        migrations.CreateModel(
            name='Ticket_ordered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Ticket price')),
                ('place', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketStore.order')),
                ('poster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.poster')),
                ('tier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.tier')),
            ],
        ),
    ]
