# Generated by Django 3.2.9 on 2021-11-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='availability',
            field=models.BooleanField(verbose_name='Availability'),
        ),
    ]
