# Generated by Django 3.2.9 on 2021-12-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketStore', '0002_auto_20211230_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=1978, verbose_name='Date'),
        ),
    ]
