# Generated by Django 3.2.9 on 2021-12-29 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketStore', '0003_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
