# Generated by Django 3.2.9 on 2021-11-24 18:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performance', '0001_initial'),
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name of requisite')),
            ],
        ),
        migrations.CreateModel(
            name='RequisiteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Type of requisite')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitePosterRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.poster')),
                ('requisite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisite.requisite')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.role')),
            ],
        ),
        migrations.CreateModel(
            name='RequisiteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='History of requisite')),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price of requisite')),
                ('requisite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisite.requisite')),
            ],
        ),
        migrations.AddField(
            model_name='requisite',
            name='requisite_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisite.requisitetype'),
        ),
    ]
